# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XCODECloudSampleiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Highcharts'

  # Pods for XCODECloudSampleiOS

  target 'XCODECloudSampleiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XCODECloudSampleiOSUITests' do
    # Pods for testing
  end

end
